# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: italo041
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: sls-express-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sls-express-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    APPOINTMENTS_REQUEST_TABLE: ${self:service}-appointments-requests-${opt:stage, 'dev'}
    SNS_TOPIC_ARN: arn:aws:sns:${self:provider.region}:${env:AWS_ACCOUNT_ID}:${self:service}-schedule-topic-${opt:stage, 'dev'}
    
    DB_HOST_PE: ${env:DB_HOST_PE}
    DB_PORT_PE: ${env:DB_PORT_PE, '3306'}
    DB_USERNAME_PE: ${env:DB_USERNAME_PE}
    DB_PASSWORD_PE: ${env:DB_PASSWORD_PE}
    DB_NAME_PE: ${env:DB_NAME_PE}

    DB_HOST_CL: ${env:DB_HOST_CL}
    DB_PORT_CL: ${env:DB_PORT_CL, '3306'}
    DB_USERNAME_CL: ${env:DB_USERNAME_CL}
    DB_PASSWORD_CL: ${env:DB_PASSWORD_CL}
    DB_NAME_CL: ${env:DB_NAME_CL}

    EVENT_BUS_NAME: ${env:EVENT_BUS_NAME, 'event_bus_appointments'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - 'Fn::GetAtt': [AppointmentsRequestTable, Arn]
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - Ref: ScheduleTopic
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - sqs:SendMessage
          Resource:
            - 'Fn::GetAtt': [SqsPeQueue, Arn]
            - 'Fn::GetAtt': [SqsClQueue, Arn]
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: 
            - arn:aws:events:${self:provider.region}:*:event-bus/*
            - arn:aws:events:${self:provider.region}:*:event-bus/event_bus_appointments

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  api:
    handler: src/infrastructure/handlers/api.handler.handler
    events:
      - httpApi: '*'
  sqsHandler:
    handler: src/infrastructure/handlers/sqs.handler.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [AppointmentsEventsQueue, Arn]
          batchSize: 10
  appointmentPeHandler:
    handler: src/infrastructure/handlers/appointment-pe.handler.handler
    timeout: 30
    logRetentionInDays: 14
    events:
      - sqs:
          arn: 
            Fn::GetAtt: [SqsPeQueue, Arn]
          batchSize: 10
  appointmentClHandler:
    handler: src/infrastructure/handlers/appointment-cl.handler.handler
    timeout: 30
    logRetentionInDays: 14
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SqsClQueue, Arn]
          batchSize: 10

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3011
  dotenv:
    path: .env
    logging: true
    include:
      - AWS_ACCOUNT_ID
      - DB_HOST_PE
      - DB_PORT_PE
      - DB_USERNAME_PE
      - DB_PASSWORD_PE
      - DB_NAME_PE
      - EVENT_BUS_NAME
      - DB_HOST_CL
      - DB_PORT_CL
      - DB_USERNAME_CL
      - DB_PASSWORD_CL
      - DB_NAME_CL

resources:
  Resources:
    # DynamoDB Table for Appointments Requests
    AppointmentsRequestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-appointments-requests-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: insureId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: insureId-index
            KeySchema:
              - AttributeName: insureId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        Tags:
          - Key: Environment
            Value: ${opt:stage, 'dev'}
          - Key: Service
            Value: ${self:service}

    # SNS Topic
    ScheduleTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-schedule-topic-${opt:stage, 'dev'}
        DisplayName: Schedule Notifications Topic
        Tags:
          - Key: Environment
            Value: ${opt:stage, 'dev'}
          - Key: Service
            Value: ${self:service}

    # SQS Queue for Peru
    SqsPeQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-sqs-pe-${opt:stage, 'dev'}
        VisibilityTimeout: 300
        MessageRetentionPeriod: 1209600
        Tags:
          - Key: Environment
            Value: ${opt:stage, 'dev'}
          - Key: Service
            Value: ${self:service}
          - Key: Country
            Value: PE

    # SQS Queue for Chile
    SqsClQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-sqs-cl-${opt:stage, 'dev'}
        VisibilityTimeout: 300
        MessageRetentionPeriod: 1209600
        Tags:
          - Key: Environment
            Value: ${opt:stage, 'dev'}
          - Key: Service
            Value: ${self:service}
          - Key: Country
            Value: CL

    # SQS Queue Policy for Peru
    SqsPeQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SqsPeQueue
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action:
                - sqs:SendMessage
              Resource:
                Fn::GetAtt: [SqsPeQueue, Arn]
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: ScheduleTopic

    # SQS Queue Policy for Chile
    SqsClQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SqsClQueue
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action:
                - sqs:SendMessage
              Resource:
                Fn::GetAtt: [SqsClQueue, Arn]
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: ScheduleTopic

    # SNS Subscription for Peru SQS
    SqsPeSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: ScheduleTopic
        Protocol: sqs
        Endpoint:
          Fn::GetAtt: [SqsPeQueue, Arn]
        FilterPolicy:
          country: ["PE"]

    # SNS Subscription for Chile SQS
    SqsClSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: ScheduleTopic
        Protocol: sqs
        Endpoint:
          Fn::GetAtt: [SqsClQueue, Arn]
        FilterPolicy:
          country: ["CL"]

    # EventBridge Custom Event Bus
    AppointmentsEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${env:EVENT_BUS_NAME, 'event_bus_appointments'}
        Tags:
          - Key: Environment
            Value: ${opt:stage, 'dev'}
          - Key: Service
            Value: ${self:service}

    # SQS Queue for Appointment Events
    AppointmentsEventsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-appointments-events-${opt:stage, 'dev'}
        VisibilityTimeout: 180
        MessageRetentionPeriod: 1209600 # 14 días
        ReceiveMessageWaitTimeSeconds: 20
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt AppointmentsEventsDeadLetterQueue.Arn
          maxReceiveCount: 3

    # Dead Letter Queue for Appointment Events
    AppointmentsEventsDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-appointments-events-dlq-${opt:stage, 'dev'}
        MessageRetentionPeriod: 1209600 # 14 días

    # EventBridge Rule for Appointment Events
    AppointmentsEventsRule:
      Type: AWS::Events::Rule
      Properties:
        Name: ${self:service}-appointments-events-rule-${opt:stage, 'dev'}
        Description: "Captura eventos de appointments creados"
        EventBusName: !Ref AppointmentsEventBus
        EventPattern:
          source:
            - "appointments.source"
          detail-type:
            - "Appointment Created"
        State: ENABLED
        Targets:
          - Arn: !GetAtt AppointmentsEventsQueue.Arn
            Id: "AppointmentsEventsQueueTarget"

    # SQS Queue Policy for Appointment Events
    AppointmentsEventsQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref AppointmentsEventsQueue
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action:
                - sqs:SendMessage
              Resource: !GetAtt AppointmentsEventsQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !GetAtt AppointmentsEventsRule.Arn

  Outputs:
    AppointmentsEventBus:
      Description: EventBridge Custom Event Bus for Appointments
      Value:
        Ref: AppointmentsEventBus
      Export:
        Name: ${self:service}-appointments-event-bus-${opt:stage, 'dev'}

    AppointmentsRequestTable:
      Description: DynamoDB Table for Appointments Requests
      Value:
        Ref: AppointmentsRequestTable
      Export:
        Name: ${self:service}-appointments-requests-table-${opt:stage, 'dev'}
    
    ScheduleTopic:
      Description: SNS Topic for Schedule Notifications
      Value:
        Ref: ScheduleTopic
      Export:
        Name: ${self:service}-schedule-topic-${opt:stage, 'dev'}
    
    SqsPeQueue:
      Description: SQS Queue for Peru
      Value:
        Ref: SqsPeQueue
      Export:
        Name: ${self:service}-sqs-pe-queue-${opt:stage, 'dev'}
    
    SqsClQueue:
      Description: SQS Queue for Chile
      Value:
        Ref: SqsClQueue
      Export:
        Name: ${self:service}-sqs-cl-queue-${opt:stage, 'dev'}

    AppointmentsEventsQueueUrl:
      Description: "URL de la cola SQS para eventos de appointments"
      Value: !Ref AppointmentsEventsQueue
      Export:
        Name: ${self:service}-appointments-events-queue-url-${opt:stage, 'dev'}

    AppointmentsEventsQueueArn:
      Description: "ARN de la cola SQS para eventos de appointments"
      Value: !GetAtt AppointmentsEventsQueue.Arn
      Export:
        Name: ${self:service}-appointments-events-queue-arn-${opt:stage, 'dev'}
