# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: italo041
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: sls-express-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sls-express-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    SCHEDULES_TABLE: ${self:service}-schedules-${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "Fn::GetAtt": [SchedulesTable, Arn]

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

custom:
  serverless-offline:
    httpPort: 3000

resources:
  Resources:
    SchedulesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-schedules-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: insureId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: insureId-index
            KeySchema:
              - AttributeName: insureId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        Tags:
          - Key: Environment
            Value: ${opt:stage, 'dev'}
          - Key: Service
            Value: ${self:service}

  Outputs:
    SchedulesTable:
      Description: DynamoDB Table for Schedules
      Value:
        Ref: SchedulesTable
      Export:
        Name: ${self:service}-schedules-table-${opt:stage, 'dev'}
